name: Build

on:
  push:
  release:
  workflow_dispatch:

env:
  BUILD_TOOLS: ${{ github.workspace }}/BuildTools
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ${{ env.BUILD_TOOLS }}
          key: build-${{ github.run_id }}
          restore-keys: |
            build-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 'current'

      - name: Install Spigot dependencies
        run: |
          [ -d '${{ env.BUILD_TOOLS }}' ] || mkdir '${{ env.BUILD_TOOLS }}'
          cd '${{ env.BUILD_TOOLS }}'
          wget -O BuildTools.jar 'https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar'
          java -jar BuildTools.jar --rev 1.8.8
          java -jar BuildTools.jar --rev 1.12.2

      - name: Checkout PaperSpigot 1.8.8
        uses: actions/checkout@v3
        with:
          repository: 'Electroid/SportPaper'
          path: ${{ env.BUILD_TOOLS }}/PaperSpigot_1.8.8
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Spigot dependencies
        run: |
          cd '${{ env.BUILD_TOOLS }}'
          java -jar BuildTools.jar --rev 1.14.4
          java -jar BuildTools.jar --rev 1.15.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Paper 1.8.8 dependencies
        run: |
          cd '${{ env.BUILD_TOOLS }}/PaperSpigot_1.8.8'
          ./sportpaper setup
          ./sportpaper patch
          mvn --batch-mode -T 1C install

      - name: Install Spigot dependencies
        run: |
          cd '${{ env.BUILD_TOOLS }}'
          java -jar BuildTools.jar --disable-java-check --rev 1.16.5
          java -jar BuildTools.jar --rev 1.17.1
          java -jar BuildTools.jar --rev 1.18.2
          java -jar BuildTools.jar --rev 1.19.2

      - name: Build with Gradle
        run: gradle build

      - uses: actions/upload-artifact@v3
        with:
          name: ArenaRegen
          path: out/ArenaRegen-*.jar
